### PR TITLE
LP-1780 Discovery and Credentials

### PR DESCRIPTION
**Pull request by aliassad**
Added start and stop commands for both applications also added them in philu provision_philu.sh

### CODE REVIEW

**Comment by ahmed-faraz46** [comment]
@aliassad please also push the changes required in `repo.sh`

**Comment by aliassad** [comment]
> @aliassad please also push the changes required in `repo.sh`

Done

**Review by emraan004 — APPROVED** [review]
👍

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍

**Pull request merged**
